# The URL the site will be built for
base_url = "https://lunnova.dev/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "lunar-zen"

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

title = "lunnova.dev"
description = "Luna Nova's blog. Opinion pieces and deep dives into tech, security, Linux systems, and software development."

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
meta_author = "LunNova (Luna Nova)"
author = "Luna Nova"
github = "LunNova"
head_comment = "Page by Lun - https://github.com/LunNova"
twitter = false
#icon = "icon.png"
#icon_alt = "avatar image of a crescent moon"
license = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\"><img alt=\"Creative Commons License CC BY-NC-SA\" style=\"vertical-align:middle;border-width:0\" width=80 height=15 src=\"/by-nc-sa-80x15.png\" /></a>"
license_url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"