# SPDX-FileCopyrightText: 2025 LunNova
#
# SPDX-License-Identifier: CC0-1.0

[toolchain]
channel = "nightly"
components = ["rust-analyzer", "rust-src", "clippy", "miri"]
targets = []
profile = "default"
