[site]
title = "lunnova.dev"
base_url = "https://lunnova.dev/"
pages_dir = "content"
description = "Luna Nova's site. GPGPU compute & build systems, Rust, hardware hacking, opinion pieces."
baseline_date = "2026-03-14"
embed_images_dir = "og-images"

[features]
hex_navigation = false
wiki_links = true
qrh = true

[theme]
dir = "theme"

[extra]
meta_author = "LunNova (Luna Nova)"
author = "Luna Nova"
github = "LunNova"
license = "<a title=\"© Luna Nova CC-BY-NC-SA 4.0\" rel=\"license nofollow\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\"><img alt=\"Creative Commons License CC BY-NC-SA\" width=88 height=31 src=\"/by-nc-sa-88x31.png\" /></a>"
license_url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
